@startuml
title "Players and Teams Use Cases"

left to right direction

actor "Fan"
actor "Administrator"

Administrator --|> Fan

rectangle "Football Management System" {
  
  package "Viewing Features" {
    usecase "View Team List" as UC_ViewTeams
    usecase "View Team Details" as UC_ViewTeamDetail
    usecase "View Player List" as UC_ViewPlayers
    usecase "View Player Details" as UC_ViewPlayerDetail
    usecase "View Coach List" as UC_ViewCoaches
    usecase "View Coach Details" as UC_ViewCoachDetail
  }

  package "Administrative Features" {
    usecase "Create New Team" as UC_CreateTeam
    usecase "Create New Player" as UC_CreatePlayer
    usecase "Create New Coach" as UC_CreateCoach
    usecase "Sign Player to a Contract" as UC_SignContract
    usecase "Assign Coach to Team" as UC_AssignCoach
    usecase "Unassign Coach from Team" as UC_UnassignCoach
  }
}


Fan -- (Viewing Features)

Administrator -- (Administrative Features)


UC_ViewTeamDetail .up.> UC_ViewTeams : <<extends>>
UC_ViewPlayerDetail .up.> UC_ViewPlayers : <<extends>>
UC_ViewCoachDetail .up.> UC_ViewCoaches : <<extends>>

UC_ViewTeamDetail ..> UC_ViewCoachDetail : <<includes>>
UC_ViewTeamDetail ..> UC_ViewPlayers : <<includes>>

UC_AssignCoach .up.> UC_ViewTeamDetail : <<extends>>
UC_UnassignCoach .up.> UC_ViewTeamDetail : <<extends>>
UC_SignContract .up.> UC_ViewTeamDetail : <<extends>>

@enduml